version: '3.8'

services:
  # PostgreSQL Databases
  postgres-auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: synergyflow_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - synergyflow-network

  postgres-workspace:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: synergyflow_workspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-workspace-data:/var/lib/postgresql/data
    networks:
      - synergyflow-network

  postgres-task:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: synergyflow_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-task-data:/var/lib/postgresql/data
    networks:
      - synergyflow-network

  # Redis for caching and real-time notifications
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - synergyflow-network

  # RabbitMQ for async messaging
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - synergyflow-network

  # Service Discovery (Eureka)
  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - synergyflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - service-discovery
      - redis
    networks:
      - synergyflow-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_NAME: synergyflow_auth
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - service-discovery
      - postgres-auth
    networks:
      - synergyflow-network

  # Workspace Service
  workspace-service:
    build:
      context: ./workspace-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      DB_HOST: postgres-workspace
      DB_PORT: 5432
      DB_NAME: synergyflow_workspace
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - service-discovery
      - postgres-workspace
    networks:
      - synergyflow-network

  # Task Service
  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      DB_HOST: postgres-task
      DB_PORT: 5432
      DB_NAME: synergyflow_task
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - service-discovery
      - postgres-task
      - rabbitmq
    networks:
      - synergyflow-network

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - service-discovery
      - redis
      - rabbitmq
    networks:
      - synergyflow-network

  # Reporting Service
  reporting-service:
    build:
      context: ./reporting-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    networks:
      - synergyflow-network

networks:
  synergyflow-network:
    driver: bridge

volumes:
  postgres-auth-data:
  postgres-workspace-data:
  postgres-task-data:
